# application.yml
server:
  port: ${PORT:8080}
spring:
  application:
    name: funds
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:clberrio4@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:jpfm vtpz bucu fpxb}
    from: ${SPRING_MAIL_FROM:fondofpv@noreply.com}
    subject: ${SPRING_MAIL_SUBJECT:Fondo Voluntario de Pensión FPV}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_SMTP_STARTTLS_ENABLE:true}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

app:
  region: ${AWS_REGION:us-east-1}
  dynamo:
    table: ${DYNAMO_TABLE:mi-tabla}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

---
spring:
  config:
    activate:
      on-profile: local
app:
  dynamo:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:http://localhost:8000}

---
spring:
  config:
    activate:
      on-profile: prod
app:
  dynamo:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:}
